CREATE TABLE dishes (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	description TEXT NOT NULL,
	price DECIMAL(10, 2) NOT NULL,
	img_url VARCHAR(120) DEFAULT NULL,
	store_id BIGINT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);
