CREATE TABLE clients (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	phone_number VARCHAR(15) NOT NULL,
	email VARCHAR(45) NOT NULL,
	password VARCHAR(255) NOT NULL,
	img_url VARCHAR(120) DEFAULT NULL,
	PRIMARY KEY(id),
	UNIQUE INDEX uq_email (email)
);

