CREATE TABLE addresses (
	id BIGINT NOT NULL AUTO_INCREMENT,
	address VARCHAR(120) NOT NULL,
	complement VARCHAR(60) NOT NULL,
	city VARCHAR(50) NOT NULL,
	state VARCHAR(50) NOT NULL,
	cep VARCHAR(20) NOT NULL,
	client_id BIGINT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

