CREATE TABLE orderitem (
	id BIGINT NOT NULL AUTO_INCREMENT,
	order_id BIGINT NOT NULL,
	dish_id BIGINT NOT NULL,
	name VARCHAR(100) NOT NULL,
	description TEXT NOT NULL,
	price DECIMAL(10, 2) NOT NULL,
	img_url VARCHAR(120) DEFAULT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY (order_id) REFERENCES orders(id),
	FOREIGN KEY (dish_id) REFERENCES dishes(id)
);

